server:
  port: 8002
  #need set redis again in cms module
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 63899
    password: 123456

    timeout: 1800000
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    lettuce:
      pool:
        #
        max-wait: -1
        #
        max-idle: 5
        min-idle: 0
        max-active: 20
