server:
  port: 8001

spring:
  datasource:
    ds1:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/erp
      username: root
      password: root
      #for druid
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 from DUAL
      etstWhileIdle: true
      testOnBorrow: false
      estOnReturn: false
      PoolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #useGlobalDataSourceStat: true
      minEvictableIdleTImeMillis: 300000

    ds2:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/erp
      username: root
      password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 63899
    password: 123456

    timeout: 1800000
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    lettuce:
      pool:
        #
        max-wait: -1
        #
        max-idle: 5
        min-idle: 0
        max-active: 20
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content: text/html
    cache: false
    prefix: classpath:/templates/

jwt:
  header: Authorization
  expire: 86400
  secret: qwertyuiopazsxdcfvgbhnjmklouhgsd
#mybatis:
  #mapper-locations: classpath:/mappers/*Mapper.xml
  #type-aliases-package: org.openjweb.sys.entity
